version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo
    ports:
      - "8080:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data     
      
      

volumes:
  postgres_data:
